trigger:
- master
- develop
- /^hotfix.*$/
- /^feature.*$/

variables:
  vmImageName: 'macos-latest'

stages:

- stage: Tests
  displayName: Tests stage
  jobs:
  - job: FastlaneTests
    displayName: FastlaneTests
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: fastlane ios tests

- stage: Compatibility
  displayName: Compatibility stage
  jobs:
  - job: DependencyManagerCompatibility
    displayName: DependencyManagerCompatibility
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: fastlane ios compatibilityTests